name: Release

on:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm install
          export NODE_ENV=production
          npm run build:dll
          npm run build

      - name: Compress assets to zip from folder
        uses: actions/zip-artifact@v2
        with:
          name: 'dist.zip'
          path: './dist'

      - name: Release
        uses: softprops/action-gh-release@v1

        with:
          file: 'dist.zip'
