name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install & Build
        run: |
          npm install
          export NODE_ENV=production
          npm run build:dll
          npm run build

      - name: Compress assets to zip from folder
        uses: vimtor/action-zip@v1
        with:
          files: dist
          dest: dist.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{ github.sha }}'
          files: 'dist.zip'
